In [3]:
import numpy as np
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]
revenus = np.array(liste)
haut_revenus = revenus[revenus>3000]
somme = revenus.sum()
moyenne = revenus.mean()
revenus[6] = revenus[6]+200
print(revenus)
revenus.dtype

[1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]


dtype('int32')

In [5]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]
data = np.array(tableau)
print(data[4,:])
mensualite_max = data[4,0] * 0.35
print(mensualite_max)
louise = [1900, 31, 1]
np.vstack((data,louise))
revenu = data[:,0]
print(revenu)


[2172   37    2]
760.1999999999999
[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
